services:
  app:    
    environment:
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    restart: always
    ports:
      - "80:5173" # 👈 Inner port 80 to be mapped to outer port 5173 of Vite
    environment:
      # React (prohlížeč) bude posílat požadavky přímo na vaši veřejnou IP
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - app
      

      