version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres      # Opraveno z DB_USER
      - POSTGRES_PASSWORD=postgres  # Opraveno z DB_PASSWORD
      - POSTGRES_DB=DB              # Opraveno z DB_NAME
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/01-seed.sql

  app:
    build: .
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --workers 4
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=DB
    depends_on:
      - db

volumes:
  postgres_data: