
services:
  app:
    environment:
      APP_ENV: local
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      # Povolí live-reload kódování přímo na vašem PC
      - ./UI:/app
      - /app/node_modules
    depends_on:
      - app

volumes:
  postgres_data:

