
services:
  app:
    build: .
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --workers 4
    ports:
      - "8080:8080"
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    build:
      context: ./UI # Cesta ke složce s Reactem
      dockerfile: Dockerfile
    depends_on:
      - app